# Generated by Django 5.2 on 2025-05-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_regular_account',
            field=models.BooleanField(default=False),
        ),
    ]
