services:
  - type: web
    name: websysproj
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn project.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OAUTH_GOOGLE_CLIENT_ID
        sync: false
      - key: OAUTH_GOOGLE_SECRET
        sync: false
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: websysproj_db
          property: connectionString
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        sync: false

databases:
  - name: websysproj_db
    databaseName: websysproj
    user: websysproj_user 